export {PrincipalPage} from './principal/principal';
export {AbecedarioPage} from './abecedario/abecedario';
export {ColoresPage} from './colores/colores';
export {DiasPage} from './dias/dias';
export {MesesPage} from './meses/meses';
export {NumerosPage} from './numeros/numeros';
export {AnimalesPage} from './animales/animales';
export {MamiferosPage} from './mamiferos/mamiferos';
export {AvesPage} from './aves/aves';
export {PecesPage} from './peces/peces';
export {ReptilesPage} from './reptiles/reptiles';
export {AnfibiosPage} from './anfibios/anfibios';
export {AntropodosPage} from './antropodos/antropodos';
export {IntermedioPage} from './intermedio/intermedio';
export {ProfesionesPage} from './profesiones/profesiones';
export {FrutasPage} from './frutas/frutas';
export {TransportePage} from './transporte/transporte';
export { MaritimoPage} from './maritimo/maritimo';
export {AereoPage} from './aereo/aereo';
export {TerrestrePage} from './terrestre/terrestre';
export {FruhoPage} from './fruho/fruho';
export {HortalizasPage} from './hortalizas/hortalizas';
export {RelojPage} from './reloj/reloj';
export {HoramPage} from './horam/horam';
export {HoratPage} from './horat/horat';
export {DeportesPage} from './deportes/deportes';

